# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ab64fb843ca2204ace0d495ce99f0639c44021619c9d002873a417bedd172ebb7088872d68c134ac52e1ddb4440f2ca7f670dd9c8291918ccdd490f08ca55a

test:
  secret_key_base: cbedf2f9a1416c80e7014614e293dad35814cc5269e0ad738911c9e6b5245f7e71f1df658a4b35669b1fc088ea3e36dcee110f03cd9f03ced78c70e3420492c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
